export const REGISTRATION_STARTS = "REGISTRATION_STARTS"
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS"
export const REGISTRATION_ERROR = "REGISTRATION_ERROR"

export const AUTH_STARTS = "AUTH_STARTS"
export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const AUTH_ERROR = "AUTH_ERROR"

export const LOGOUT_USER = "LOGOUT_USER"

export const ADD_GRATITUDE_STARTS = "ADD_GRATITUDE_STARTS"
export const ADD_GRATITUDE_SUCCESS = "ADD_GRATITUDE_SUCCESS"
export const ADD_GRATITUDE_ERROR = "ADD_GRATITUDE_ERROR"

export const UPDATING_GRATITUDE_START = "UPDATING_GRATITUDE_START"
export const UPDATING_GRATITUDE_SUCCESS = "UPDATING_GRATITUDE_SUCCESS"
export const UPDATING_GRATITUDE_ERROR = "UPDATING_GRATITUDE_ERROR"

export const DELETING_GRATITUDE_START = "DELETING_GRATITUDE_START"
export const DELETING_GRATITUDE_SUCCESS = "DELETING_GRATITUDE_SUCCESS"
export const DELETING_GRATITUDE_ERROR = "DELETING_GRATITUDE_ERROR"
    
export const FETCHING_GRATITUDE_START = "FETCHING_GRATITUDE_START"
export const FETCHING_GRATITUDE_SUCCESS = "FETCHING_GRATITUDE_SUCCESS"
export const FETCHING_GRATITUDE_ERROR = "FETCHING_GRATITUDE_ERROR"

export const FETCHING_GRATITUDES_START = "FETCHING_GRATITUDES_START"
export const FETCHING_GRATITUDES_SUCCESS = "FETCHING_GRATITUDES_SUCCESS"
export const FETCHING_GRATITUDES_ERROR = "FETCHING_GRATITUDES_ERROR"

export const FETCHING_USER_GRATITUDES_START = "FETCHING_USER_GRATITUDES_START"
export const FETCHING_USER_GRATITUDES_SUCCESS = "FETCHING_USER_GRATITUDES_SUCCESS"
export const FETCHING_USER_GRATITUDES_ERROR = "FETCHING_USER_GRATITUDES_ERROR"
